# Generated by Django 3.1.6 on 2021-11-30 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0072_remove_produit_taille_pizza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='est_accompagnement',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='est_boissons',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='est_burger',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='est_dessert',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='est_entree',
        ),
    ]
