# Generated by Django 3.1.6 on 2021-12-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0073_auto_20211130_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneLivraison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('montant', models.FloatField(blank=True, default=0)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
    ]
