# Generated by Django 3.1.6 on 2021-12-20 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0074_zonelivraison'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='type_ingredient',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='typeIngredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.typeingredient'),
        ),
    ]
