# Generated by Django 3.1.6 on 2021-12-20 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0076_typesupplement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplement',
            name='type_supplement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.typeingredient'),
        ),
    ]
