# Generated by Django 3.1.6 on 2021-12-20 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0078_auto_20211220_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplement',
            name='sup_burgers_sandwichs_assiettes',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='sup_family',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='sup_milshake_crepe',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='sup_mix_viande',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='sup_pizzas',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='sup_salade',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='sup_salee',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='sup_smoothie',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='sup_sucree',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='sup_sur_frite',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='sup_tacos',
        ),
    ]
