# Generated by Django 3.1.6 on 2021-12-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0079_auto_20211220_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplement',
            name='supp_viande',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
