# Generated by Django 3.1.6 on 2021-12-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0080_supplement_supp_viande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplement',
            name='supp_viande',
        ),
        migrations.AddField(
            model_name='supplement',
            name='type',
            field=models.CharField(choices=[(1, 'supp_viande'), (2, 'supp_fromage')], default=1, max_length=1),
        ),
    ]
