# Generated by Django 3.1.6 on 2021-12-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0081_auto_20211220_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplement',
            name='type',
            field=models.CharField(choices=[(1, 'supp_viande'), (2, 'supp_fromage')], default=1, max_length=5),
        ),
    ]
