# Generated by Django 3.1.6 on 2021-12-21 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0082_auto_20211220_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplement',
            name='type',
        ),
    ]
