# Generated by Django 3.1.6 on 2021-12-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0083_remove_supplement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='supplement',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
