# Generated by Django 3.1.6 on 2021-12-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0084_ingredient_supplement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='supplement',
        ),
        migrations.AddField(
            model_name='produit',
            name='supplement',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
