# Generated by Django 3.1.6 on 2021-12-21 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0085_auto_20211221_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.categorie'),
        ),
    ]
