# Generated by Django 3.1.6 on 2021-12-22 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0086_ingredient_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplement',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.categorie'),
        ),
    ]
