# Generated by Django 3.1.6 on 2021-12-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0087_supplement_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='disponibilite',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
