# Generated by Django 3.1.6 on 2022-02-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0089_zonelivraison_frais'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_restaurant',
            name='automatique',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
